function recording = load_real_edf( ...
    filePath, ...
    channelIndex, ...
    startSeconds, ...
    durationSeconds ...
)
%LOAD_REAL_EDF Read part of one EDF channel through Python.
%
% channelIndex uses MATLAB's one-based indexing.
%
% Example:
%
% recording = load_real_edf( ...
%     "/path/to/file.edf", ...
%     1, ...
%     0, ...
%     60 ...
% );

arguments
    filePath (1, 1) string
    channelIndex (1, 1) double {mustBeInteger, mustBePositive} = 1
    startSeconds (1, 1) double {mustBeNonnegative} = 0
    durationSeconds (1, 1) double {mustBePositive} = 60
end

if ~isfile(filePath)
    error( ...
        "SEEG:EDFFileNotFound", ...
        "The EDF file does not exist:%s%s", ...
        newline, ...
        filePath ...
    );
end

pyedflib = py.importlib.import_module("pyedflib");

reader = pyedflib.EdfReader(char(filePath));
readerCleanup = onCleanup(@() reader.close()); %#ok<NASGU>

numberOfChannels = double(reader.signals_in_file);

if channelIndex > numberOfChannels
    error( ...
        "SEEG:ChannelNotFound", ...
        "The EDF contains %d channels, but channel %d was requested.", ...
        numberOfChannels, ...
        channelIndex ...
    );
end

pythonChannelIndex = channelIndex - 1;

labels = cell(reader.getSignalLabels());
channelLabel = string(labels{channelIndex});

samplingFrequency = double( ...
    reader.getSampleFrequency(int32(pythonChannelIndex)) ...
);

sampleCounts = double(reader.getNSamples());
totalSamples = sampleCounts(channelIndex);

startSample = floor(startSeconds * samplingFrequency);
requestedSamples = floor(durationSeconds * samplingFrequency);

if startSample >= totalSamples
    error( ...
        "SEEG:StartOutsideRecording", ...
        "The requested start time is outside the recording." ...
    );
end

availableSamples = totalSamples - startSample;
samplesToRead = min(requestedSamples, availableSamples);

pythonSignal = reader.readSignal( ...
    int32(pythonChannelIndex), ...
    pyargs( ...
        "start", int64(startSample), ...
        "n", int64(samplesToRead) ...
    ) ...
);

signal = double(pythonSignal);
signal = signal(:)';

if isempty(signal)
    error( ...
        "SEEG:EmptyEDFSignal", ...
        "No signal values were returned from the EDF file." ...
    );
end

if ~all(isfinite(signal))
    error( ...
        "SEEG:InvalidEDFSignal", ...
        "The selected EDF segment contains NaN or infinite values." ...
    );
end

recording.filePath = filePath;
recording.channelIndex = channelIndex;
recording.channelLabel = channelLabel;
recording.fs = samplingFrequency;
recording.startSeconds = startSeconds;
recording.durationSeconds = numel(signal) / samplingFrequency;
recording.signal = signal;
recording.numberOfChannels = numberOfChannels;
recording.totalSamples = totalSamples;

end