function tests = test_metrics_api_positive
% Positive MATLAB integration tests for gui.api.metrics_api.

tests = functiontests(localfunctions);
end


function setupOnce(testCase)
% Add the shared helper and mock-data folders.

integrationTestsFolder = fileparts(mfilename("fullpath"));
matlabTestsFolder = fileparts(integrationTestsFolder);

addpath(fullfile(matlabTestsFolder, "helpers"));
addpath(fullfile(matlabTestsFolder, "mock_data"));

setup_python_test_environment();

testCase.TestData.api = ...
    py.importlib.import_module("gui.api.metrics_api");

testCase.TestData.mock = mock_api_positive();
end


function testPhaseErrorsCanBeCalculated(testCase)
% MATLAB sends detected and ground-truth times to Python.

api = testCase.TestData.api;
mock = testCase.TestData.mock;

detected = createPythonPhaseDictionary( ...
    mock.input.metrics.detected ...
);

groundTruth = createPythonPhaseDictionary( ...
    mock.input.metrics.groundTruth ...
);

result = api.calculate_phase_errors( ...
    detected, ...
    groundTruth ...
);

testCase.verifyEqual( ...
    double(result{py.str("onset")}), ...
    mock.expected.metrics.errors.onset ...
);

testCase.verifyEqual( ...
    double(result{py.str("transition")}), ...
    mock.expected.metrics.errors.transition ...
);

testCase.verifyEqual( ...
    double(result{py.str("termination")}), ...
    mock.expected.metrics.errors.termination ...
);
end


function testCompleteEvaluationCanBeReturned(testCase)
% Python should return the expected count, MAE, RMSE, median, IQR,
% and accuracy.

api = testCase.TestData.api;
mock = testCase.TestData.mock;

detected = createPythonPhaseDictionary( ...
    mock.input.metrics.detected ...
);

groundTruth = createPythonPhaseDictionary( ...
    mock.input.metrics.groundTruth ...
);

result = api.evaluate_detections( ...
    detected, ...
    groundTruth, ...
    mock.input.metrics.tolerance ...
);

summary = result{py.str("summary")};

testCase.verifyEqual( ...
    double(summary{py.str("n")}), ...
    mock.expected.metrics.count ...
);

testCase.verifyEqual( ...
    double(summary{py.str("mae")}), ...
    mock.expected.metrics.mae, ...
    "AbsTol", 1e-12 ...
);

testCase.verifyEqual( ...
    double(summary{py.str("rmse")}), ...
    mock.expected.metrics.rmse, ...
    "AbsTol", 1e-12 ...
);

testCase.verifyEqual( ...
    double(summary{py.str("median")}), ...
    mock.expected.metrics.median ...
);

testCase.verifyEqual( ...
    double(summary{py.str("iqr")}), ...
    mock.expected.metrics.iqr ...
);

testCase.verifyEqual( ...
    double(summary{py.str("acc_2s")}), ...
    mock.expected.metrics.accuracy ...
);
end


function dictionary = createPythonPhaseDictionary(values)
% Convert one MATLAB phase structure into a Python dictionary.

dictionary = py.dict(pyargs( ...
    "onset", values.onset, ...
    "transition", values.transition, ...
    "termination", values.termination ...
));
end