function tests = test_metrics_api_negative
% Negative and edge-case MATLAB tests for gui.api.metrics_api.

tests = functiontests(localfunctions);
end


function setupOnce(testCase)
% Add the shared helper and mock-data folders.

integrationTestsFolder = fileparts(mfilename("fullpath"));
matlabTestsFolder = fileparts(integrationTestsFolder);

addpath(fullfile(matlabTestsFolder, "helpers"));
addpath(fullfile(matlabTestsFolder, "mock_data"));

setup_python_test_environment();

testCase.TestData.api = ...
    py.importlib.import_module("gui.api.metrics_api");

testCase.TestData.mock = mock_api_negative();
end


function testMissingDetectionReturnsNaNError(testCase)
% A missing transition should produce a NaN transition error.

api = testCase.TestData.api;
mock = testCase.TestData.mock;

detected = py.dict(pyargs( ...
    "onset", ...
        mock.input.metrics.detectedWithMissingValue.onset, ...
    "transition", py.None, ...
    "termination", ...
        mock.input.metrics.detectedWithMissingValue.termination ...
));

groundTruth = py.dict(pyargs( ...
    "onset", mock.input.metrics.groundTruth.onset, ...
    "transition", mock.input.metrics.groundTruth.transition, ...
    "termination", mock.input.metrics.groundTruth.termination ...
));

result = api.calculate_phase_errors( ...
    detected, ...
    groundTruth ...
);

testCase.verifyEqual( ...
    double(result{py.str("onset")}), ...
    mock.expected.metrics.missingDetectionErrors.onset ...
);

testCase.verifyTrue( ...
    isnan(double(result{py.str("transition")})) ...
);

testCase.verifyEqual( ...
    double(result{py.str("termination")}), ...
    mock.expected.metrics.missingDetectionErrors.termination ...
);
end


function testNegativeToleranceReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

errors = py.list({1.0, 2.0, 3.0});

pythonCall = @() api.summarize_errors( ...
    errors, ...
    mock.input.metrics.negativeTolerance ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.metrics.negativeToleranceError ...
);
end


function testAllMissingValuesReturnEmptySummary(testCase)
% Empty dictionaries should return a summary with zero valid values.

api = testCase.TestData.api;
mock = testCase.TestData.mock;

detected = py.dict();
groundTruth = py.dict();

result = api.evaluate_detections( ...
    detected, ...
    groundTruth, ...
    5.0 ...
);

summary = result{py.str("summary")};

testCase.verifyEqual( ...
    double(summary{py.str("n")}), ...
    mock.expected.metrics.emptySummaryCount ...
);

testCase.verifyTrue( ...
    isnan(double(summary{py.str("mae")})) ...
);

testCase.verifyTrue( ...
    isnan(double(summary{py.str("rmse")})) ...
);
end


function verifyPythonErrorContains(testCase, pythonCall, expectedText)
% Run a Python call and confirm that its error contains expected text.

try
    pythonCall();

    testCase.verifyFail( ...
        "Python did not raise the expected error." ...
    );

catch exception
    testCase.verifySubstring( ...
        string(exception.message), ...
        string(expectedText) ...
    );
end
end