function tests = test_features_api_negative
% Negative MATLAB integration tests for gui.api.features_api.

tests = functiontests(localfunctions);
end


function setupOnce(testCase)
% Add the shared helper and mock-data folders.

integrationTestsFolder = fileparts(mfilename("fullpath"));
matlabTestsFolder = fileparts(integrationTestsFolder);

addpath(fullfile(matlabTestsFolder, "helpers"));
addpath(fullfile(matlabTestsFolder, "mock_data"));

setup_python_test_environment();

testCase.TestData.api = ...
    py.importlib.import_module("gui.api.features_api");

testCase.TestData.mock = mock_api_negative();
end


function testEmptySignalReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

pythonSignal = py.list( ...
    num2cell(mock.input.features.emptySignal) ...
);

pythonCall = @() api.validate_signal( ...
    pythonSignal, ...
    mock.input.validFs ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.features.emptySignalError ...
);
end


function testTwoDimensionalSignalReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

numpy = py.importlib.import_module("numpy");

pythonSignal = numpy.array( ...
    mock.input.features.twoDimensionalSignal ...
);

pythonCall = @() api.validate_signal( ...
    pythonSignal, ...
    mock.input.validFs ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.features.twoDimensionalSignalError ...
);
end


function testSignalWithNaNReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

numpy = py.importlib.import_module("numpy");

pythonSignal = numpy.array( ...
    mock.input.features.signalWithNaN ...
);

pythonCall = @() api.validate_signal( ...
    pythonSignal, ...
    mock.input.validFs ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.features.nonFiniteSignalError ...
);
end


function testZeroSamplingFrequencyReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

pythonSignal = py.list( ...
    num2cell(mock.input.features.validSignal) ...
);

pythonCall = @() api.validate_signal( ...
    pythonSignal, ...
    mock.input.features.zeroSamplingFrequency ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.features.invalidSamplingFrequencyError ...
);
end


function testShortSignalReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

numpy = py.importlib.import_module("numpy");

pythonSignal = numpy.array( ...
    mock.input.features.shortSignal ...
);

pythonCall = @() api.extract_features( ...
    pythonSignal, ...
    mock.input.validFs, ...
    int32(mock.input.features.largeWindowSize), ...
    int32(mock.input.features.validStep), ...
    pyargs("apply_highpass", false) ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.features.shortSignalError ...
);
end


function verifyPythonErrorContains(testCase, pythonCall, expectedText)
% Run a Python call and confirm that its error contains expected text.

try
    pythonCall();

    testCase.verifyFail( ...
        "Python did not raise the expected error." ...
    );

catch exception
    testCase.verifySubstring( ...
        string(exception.message), ...
        string(expectedText) ...
    );
end
end