function tests = test_detection_api_negative
% Negative MATLAB integration tests for gui.api.detection_api.

tests = functiontests(localfunctions);
end


function setupOnce(testCase)
% Add the shared helper and mock-data folders.

integrationTestsFolder = fileparts(mfilename("fullpath"));
matlabTestsFolder = fileparts(integrationTestsFolder);

addpath(fullfile(matlabTestsFolder, "helpers"));
addpath(fullfile(matlabTestsFolder, "mock_data"));

setup_python_test_environment();

testCase.TestData.api = ...
    py.importlib.import_module("gui.api.detection_api");

testCase.TestData.mock = mock_api_negative();
end


function testUnknownPhaseReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

numpy = py.importlib.import_module("numpy");

pythonMatrix = numpy.array( ...
    mock.input.detection.validMatrix ...
);

pythonCall = @() api.detect_phase( ...
    pythonMatrix, ...
    char(mock.input.detection.unknownPhase) ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.detection.unknownPhaseError ...
);
end


function testEmptyMatrixReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

numpy = py.importlib.import_module("numpy");

pythonMatrix = numpy.array( ...
    mock.input.detection.emptyMatrix ...
);

pythonCall = @() api.detect_phase( ...
    pythonMatrix, ...
    "onset" ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.detection.emptyMatrixError ...
);
end


function testMatrixWithNaNReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

numpy = py.importlib.import_module("numpy");

pythonMatrix = numpy.array( ...
    mock.input.detection.matrixWithNaN ...
);

pythonCall = @() api.detect_phase( ...
    pythonMatrix, ...
    "onset" ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.detection.nonFiniteMatrixError ...
);
end


function testNegativeSampleReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

samples = py.dict(pyargs( ...
    "onset", int64(mock.input.detection.negativeSample) ...
));

pythonCall = @() api.samples_to_seconds( ...
    samples, ...
    mock.input.validFs ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.detection.negativeSampleError ...
);
end


function testZeroSamplingFrequencyReturnsClearError(testCase)
api = testCase.TestData.api;
mock = testCase.TestData.mock;

samples = py.dict(pyargs( ...
    "onset", int64(1000) ...
));

pythonCall = @() api.samples_to_seconds( ...
    samples, ...
    mock.input.detection.zeroSamplingFrequency ...
);

verifyPythonErrorContains( ...
    testCase, ...
    pythonCall, ...
    mock.expected.detection.invalidSamplingFrequencyError ...
);
end


function verifyPythonErrorContains(testCase, pythonCall, expectedText)
% Run a Python call and confirm that its error contains expected text.

try
    pythonCall();

    testCase.verifyFail( ...
        "Python did not raise the expected error." ...
    );

catch exception
    testCase.verifySubstring( ...
        string(exception.message), ...
        string(expectedText) ...
    );
end
end