function tests = test_detection_api_positive
% Positive MATLAB integration tests for gui.api.detection_api.

tests = functiontests(localfunctions);
end


function setupOnce(testCase)
% Add the shared helper and mock-data folders.

integrationTestsFolder = fileparts(mfilename("fullpath"));
matlabTestsFolder = fileparts(integrationTestsFolder);

addpath(fullfile(matlabTestsFolder, "helpers"));
addpath(fullfile(matlabTestsFolder, "mock_data"));

setup_python_test_environment();

testCase.TestData.api = ...
    py.importlib.import_module("gui.api.detection_api");

testCase.TestData.mock = mock_api_positive();
end


function testSamplesCanBeConvertedToSeconds(testCase)
% MATLAB sends sample positions and receives seconds from Python.

api = testCase.TestData.api;
mock = testCase.TestData.mock;

samples = py.dict(pyargs( ...
    "onset", int64(mock.input.detection.samples.onset), ...
    "transition", int64(mock.input.detection.samples.transition), ...
    "termination", int64(mock.input.detection.samples.termination) ...
));

result = api.samples_to_seconds( ...
    samples, ...
    mock.input.fs ...
);

testCase.verifyEqual( ...
    double(result{py.str("onset")}), ...
    mock.expected.detection.seconds.onset ...
);

testCase.verifyEqual( ...
    double(result{py.str("transition")}), ...
    mock.expected.detection.seconds.transition ...
);

testCase.verifyEqual( ...
    double(result{py.str("termination")}), ...
    mock.expected.detection.seconds.termination ...
);
end


function testMatlabMatrixCanReachOnsetDetector(testCase)
% The mock matrix contains one clear change near row 40.

api = testCase.TestData.api;
mock = testCase.TestData.mock;

numpy = py.importlib.import_module("numpy");

pythonMatrix = numpy.array( ...
    mock.input.detection.featureMatrix ...
);

parameters = py.dict(pyargs( ...
    "penalty", int64(mock.input.detection.penalty) ...
));

result = api.detect_phase( ...
    pythonMatrix, ...
    char(mock.input.detection.phase), ...
    parameters ...
);

detectedIndex = double(result);

testCase.verifyGreaterThanOrEqual( ...
    detectedIndex, ...
    mock.expected.detection.changeMinimum ...
);

testCase.verifyLessThanOrEqual( ...
    detectedIndex, ...
    mock.expected.detection.changeMaximum ...
);
end


function testMissingDetectionRemainsPythonNone(testCase)
% Python None should remain readable in MATLAB.

api = testCase.TestData.api;
mock = testCase.TestData.mock;

samples = py.dict(pyargs( ...
    "onset", int64( ...
        mock.input.detection.samplesWithMissingValue.onset), ...
    "transition", py.None, ...
    "termination", int64( ...
        mock.input.detection.samplesWithMissingValue.termination) ...
));

result = api.samples_to_seconds( ...
    samples, ...
    mock.input.fs ...
);

testCase.verifyEqual( ...
    double(result{py.str("onset")}), ...
    mock.expected.detection.secondsWithMissingValue.onset ...
);

testCase.verifyClass( ...
    result{py.str("transition")}, ...
    "py.NoneType" ...
);

testCase.verifyEqual( ...
    double(result{py.str("termination")}), ...
    mock.expected.detection.secondsWithMissingValue.termination ...
);
end